services:
  app:
    build: .
    container_name: fatepet-app
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - gradle-cache:/root/.gradle
    networks:
      - fatepet-network

  mysql:
    image: mysql:8.0
    container_name: fatepet-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fatepet-network

volumes:
  mysql-data:
  gradle-cache:

networks:
  fatepet-network:
